import { IListaObjeto, IListaPalabras } from "./datos.service"
export const ListaEjemplo : object[] = [
    {"Kanjis-Jap" : [{palabra1:  'Agua', palabra2: '水', descripcion: "---", nivel: 0},
                        {palabra1: 'Fuego', palabra2: '火' , descripcion: "---", nivel: 0},
                        {palabra1: 'Tierra', palabra2: '土' , descripcion: "---", nivel: 0},
                        {palabra1: 'Viento', palabra2: '風' , descripcion: "---", nivel: 0},
                        {palabra1: 'Casa', palabra2: '家' , descripcion: "---", nivel: 0},
                        {palabra1: 'Persona', palabra2: '人' , descripcion: "---", nivel: 0},
                        {palabra1: 'Padre', palabra2: '父' , descripcion: "---", nivel: 0},
                        {palabra1: 'Madre', palabra2: '母' , descripcion: "---", nivel: 0},
                        {palabra1: 'Izquierda', palabra2: '左' , descripcion: "---", nivel: 0},
                        {palabra1: 'Derecha', palabra2: '右' , descripcion: "---", nivel: 0},
                        {palabra1: 'Cielo', palabra2: '天' , descripcion: "---", nivel: 0},
                        {palabra1: 'Mano', palabra2: '手' , descripcion: "---", nivel: 0},
                        {palabra1: 'Pie', palabra2: '足' , descripcion: "---", nivel: 0},
                        {palabra1: 'Ojo', palabra2: '目' , descripcion: "---", nivel: 0},
                        {palabra1: 'Cabello', palabra2: '髪' , descripcion: "---", nivel: 0},
                        {palabra1: 'Rápido', palabra2: '速' , descripcion: "---", nivel: 0},
                        {palabra1: 'Perro', palabra2: '犬' , descripcion: "---", nivel: 0},
                        {palabra1: 'Gato', palabra2: '猫' , descripcion: "---", nivel: 0},
                        {palabra1: 'Electricidad', palabra2: '電' , descripcion: "---", nivel: 0},
                        {palabra1: 'Comida', palabra2: '食' , descripcion: "---", nivel: 0},
                        {palabra1: 'Fuerza', palabra2: '力' , descripcion: "---", nivel: 0},
                        {palabra1: 'Alto', palabra2: '高' , descripcion: "---", nivel: 0},
                        {palabra1: 'Dormir', palabra2: '寝' , descripcion: "---", nivel: 0},
                        {palabra1: 'Caminar', palabra2: '歩' , descripcion: "---", nivel: 0},
                        {palabra1: 'Beber', palabra2: '飲' , descripcion: "---", nivel: 0},
                        {palabra1: 'Sueño', palabra2 :'夢'  , descripcion: "---", nivel: 0}]},
    {"Binario": [{palabra1 : "00000", palabra2 : "0", descripcion: "---", nivel: 0},
                        {palabra1 : "00001", palabra2 : "1", descripcion: "---", nivel: 0},
                        {palabra1 : "00010", palabra2 : "2", descripcion: "---", nivel: 0},
                        {palabra1 : "00011", palabra2 : "3", descripcion: "---", nivel: 0},
                        {palabra1 : "00100", palabra2 : "4", descripcion: "---", nivel: 0},
                        {palabra1 : "00101", palabra2 : "5", descripcion: "---", nivel: 0},
                        {palabra1 : "00110", palabra2 : "6", descripcion: "---", nivel: 0},
                        {palabra1 : "00111", palabra2 : "7", descripcion: "---", nivel: 0},
                        {palabra1 : "01000", palabra2 : "8", descripcion: "---", nivel: 0},
                        {palabra1 : "01001", palabra2 : "9", descripcion: "---", nivel: 0},
                        {palabra1 : "01010", palabra2 : "10", descripcion: "---", nivel: 0},
                        {palabra1 : "01011", palabra2 : "11", descripcion: "---", nivel: 0},
                        {palabra1 : "01100", palabra2 : "12", descripcion: "---", nivel: 0},
                        {palabra1 : "01101", palabra2 : "13", descripcion: "---", nivel: 0},
                        {palabra1 : "01110", palabra2 : "14", descripcion: "---", nivel: 0},
                        {palabra1 : "01111", palabra2 : "15", descripcion: "---", nivel: 0},
                        {palabra1 : "10000", palabra2 : "16", descripcion: "---", nivel: 0},
                        {palabra1 : "10001", palabra2 : "17", descripcion: "---", nivel: 0},
                        {palabra1 : "10010", palabra2 : "18", descripcion: "---", nivel: 0},
                        {palabra1 : "10011", palabra2 : "19", descripcion: "---", nivel: 0},
                        {palabra1 : "10100", palabra2 : "20", descripcion: "---", nivel: 0},
                        {palabra1 : "10101", palabra2 : "21", descripcion: "---", nivel: 0},
                        {palabra1 : "10110", palabra2 : "22", descripcion: "---", nivel: 0},
                        {palabra1 : "10111", palabra2 : "23", descripcion: "---", nivel: 0},
                        {palabra1 : "11000", palabra2 : "24", descripcion: "---", nivel: 0},
                        {palabra1 : "11001", palabra2 : "25", descripcion: "---", nivel: 0},
                        {palabra1 : "11010", palabra2 : "26", descripcion: "---", nivel: 0},
                        {palabra1 : "11011", palabra2 : "27", descripcion: "---", nivel: 0},
                        {palabra1 : "11100", palabra2 : "28", descripcion: "---", nivel: 0},
                        {palabra1 : "11101", palabra2 : "29", descripcion: "---", nivel: 0},
                        {palabra1 : "11110", palabra2 : "30", descripcion: "---", nivel: 0},
                        {palabra1 : "11111", palabra2 : "31", descripcion: "---", nivel: 0}]},
    {"Tabla Periodica" : [{palabra1: "Hidrógeno", palabra2: "H", descripcion : "---", nivel : 0},
                        {palabra1: "Helio", palabra2: "He",  descripcion : "---", nivel : 0 },
                        {palabra1 : "Litio", palabra2: "Li", descripcion : "---", nivel : 0},
                        {palabra1: "Berilio", palabra2: "Be", descripcion : "---", nivel : 0},
                        {palabra1: "Boro", palabra2: "B", descripcion : "---", nivel : 0},
                        {palabra1: "Carbono", palabra2: "C", descripcion : "---", nivel : 0},
                        {palabra1: "Nitrógeno", palabra2: "N", descripcion : "---", nivel : 0},
                        {palabra1: "Oxígeno", palabra2: "O", descripcion : "---", nivel : 0},
                        {palabra1: "Flúor", palabra2: "F", descripcion : "---", nivel : 0},
                        {palabra1: "Neón", palabra2: "Ne", descripcion : "---", nivel : 0},
                        {palabra1: "Sodio", palabra2: "Na", descripcion : "---", nivel : 0},
                        {palabra1: "Magnesio", palabra2: "Mg", descripcion : "---", nivel : 0},
                        {palabra1: "Aluminio", palabra2: "Al", descripcion : "---", nivel : 0},
                        {palabra1: "Silicio", palabra2: "Si", descripcion : "---", nivel : 0},
                        {palabra1: "Fósforo", palabra2: "P", descripcion : "---", nivel : 0},
                        {palabra1: "Azufre", palabra2: "S", descripcion : "---", nivel : 0},
                        {palabra1: "Cloro", palabra2: "Cl", descripcion : "---", nivel : 0},
                        {palabra1: "Argon", palabra2: "Ar", descripcion : "---", nivel : 0},
                        {palabra1: "Potasio", palabra2: "K", descripcion : "---", nivel : 0},
                        {palabra1: "Calcio", palabra2: "Ca", descripcion : "---", nivel : 0},
                        {palabra1: "Escandio", palabra2: "Sc", descripcion : "---", nivel : 0},
                        {palabra1: "Titanio", palabra2: "Ti", descripcion : "---", nivel : 0},
                        {palabra1: "Vanadio", palabra2: "V", descripcion : "---", nivel : 0},
                        {palabra1: "Cromo", palabra2: "Cr", descripcion : "---", nivel : 0},
                        {palabra1: "Manganeso", palabra2: "Mn", descripcion : "---", nivel : 0},
                        {palabra1: "Hierro", palabra2: "Fe", descripcion : "---", nivel : 0},
                        {palabra1: "Cobalto", palabra2: "Co", descripcion : "---", nivel : 0},
                        {palabra1: "Niquel", palabra2: "Ni", descripcion : "---", nivel : 0},
                        {palabra1: "Cobre", palabra2: "Cu", descripcion : "---", nivel : 0},
                        {palabra1: "Zinc", palabra2: "Zn", descripcion : "---", nivel : 0},
                        {palabra1: "Galio", palabra2: "Ga", descripcion : "---", nivel : 0},
                        {palabra1: "Germanio", palabra2: "Ge", descripcion : "---", nivel : 0},
                        {palabra1: "Arsénico", palabra2: "As", descripcion : "---", nivel : 0},
                        {palabra1: "Selenio", palabra2: "Se", descripcion : "---", nivel : 0},
                        {palabra1: "Bromo", palabra2: "Br", descripcion : "---", nivel : 0},
                        {palabra1: "Kryptón", palabra2: "Kr", descripcion : "---", nivel : 0},
                        {palabra1: "Rubidio", palabra2: "Rb", descripcion : "---", nivel : 0},
                        {palabra1: "Estroncio", palabra2: "Sr", descripcion : "---", nivel : 0},
                        {palabra1: "Itrio", palabra2: "Y", descripcion : "---", nivel : 0},
                        {palabra1: "Circonio", palabra2: "Zr", descripcion : "---", nivel : 0},
                        {palabra1: "Niobio", palabra2: "Nb", descripcion : "---", nivel : 0},
                        {palabra1: "Molibdeno", palabra2: "Mo", descripcion : "---", nivel : 0},
                        {palabra1: "Tecnecio", palabra2: "Tc", descripcion : "---", nivel : 0},
                        {palabra1: "Rutenio", palabra2: "Ru", descripcion : "---", nivel : 0},
                        {palabra1: "Rodio", palabra2: "Rh", descripcion : "---", nivel : 0},
                        {palabra1: "Paladio", palabra2: "Pd", descripcion : "---", nivel : 0},
                        {palabra1: "Plata", palabra2: "Ag", descripcion : "---", nivel : 0},
                        {palabra1: "Cadmio", palabra2: "Cd", descripcion : "---", nivel : 0},
                        {palabra1: "Indio", palabra2: "In", descripcion : "---", nivel : 0},
                        {palabra1: "Estaño", palabra2: "Sn", descripcion : "---", nivel : 0},
                        {palabra1: "Antimonio", palabra2: "Sb", descripcion : "---", nivel : 0},
                        {palabra1: "Telurio", palabra2: "Te", descripcion : "---", nivel : 0},
                        {palabra1: "Yodo", palabra2: "I", descripcion : "---", nivel : 0},
                        {palabra1: "Xenon", palabra2: "Xe", descripcion : "---", nivel : 0},
                        {palabra1: "Cesio", palabra2: "Cs", descripcion : "---", nivel : 0},
                        {palabra1: "Bario", palabra2: "Ba", descripcion : "---", nivel : 0},
                        {palabra1: "Lantano", palabra2: "La", descripcion : "---", nivel : 0},
                        {palabra1: "Cerio", palabra2: "Ce", descripcion : "---", nivel : 0},
                        {palabra1: "Praseodimio", palabra2: "Pr", descripcion : "---", nivel : 0},
                        {palabra1: "Neodimio", palabra2: "Nd", descripcion : "---", nivel : 0},
                        {palabra1: "Prometio", palabra2: "Pm", descripcion : "---", nivel : 0},
                        {palabra1: "Samario", palabra2: "Sm", descripcion : "---", nivel : 0},
                        {palabra1: "Europio", palabra2: "Eu", descripcion : "---", nivel : 0},
                        {palabra1: "Gadolinio", palabra2: "Gd", descripcion : "---", nivel : 0},
                        {palabra1: "Terbio", palabra2: "Tb", descripcion : "---", nivel : 0},
                        {palabra1: "Disprosio", palabra2: "Dy", descripcion : "---", nivel : 0},
                        {palabra1: "Holmio", palabra2: "Ho", descripcion : "---", nivel : 0},
                        {palabra1: "Erbio", palabra2: "Er", descripcion : "---", nivel : 0},
                        {palabra1: "Tulio", palabra2: "Tm", descripcion : "---", nivel : 0},
                        {palabra1: "Iterbio", palabra2: "Yb", descripcion : "---", nivel : 0},
                        {palabra1: "Lutecio", palabra2: "Lu", descripcion : "---", nivel : 0},
                        {palabra1: "Hafnio", palabra2: "Hf", descripcion : "---", nivel : 0},
                        {palabra1: "Tántalo", palabra2: "Ta", descripcion : "---", nivel : 0},
                        {palabra1: "Wolframio", palabra2: "W", descripcion : "---", nivel : 0},
                        {palabra1: "Renio", palabra2: "Re", descripcion : "---", nivel : 0},
                        {palabra1: "Osmio", palabra2: "Os", descripcion : "---", nivel : 0},
                        {palabra1: "Iridio", palabra2: "Ir", descripcion : "---", nivel : 0},
                        {palabra1: "Platino", palabra2: "Pt", descripcion : "---", nivel : 0},
                        {palabra1: "Oro", palabra2: "Au", descripcion : "---", nivel : 0},
                        {palabra1: "Mercurio", palabra2: "Hg", descripcion : "---", nivel : 0},
                        {palabra1: "Talio", palabra2: "Tl", descripcion : "---", nivel : 0},
                        {palabra1: "Plomo", palabra2: "Pb", descripcion : "---", nivel : 0},
                        {palabra1: "Bismuto", palabra2: "Bi", descripcion : "---", nivel : 0},
                        {palabra1: "Polonio", palabra2: "Po", descripcion : "---", nivel : 0},
                        {palabra1: "Ástato", palabra2: "At", descripcion : "---", nivel : 0},
                        {palabra1: "Radón", palabra2: "Rn", descripcion : "---", nivel : 0},
                        {palabra1: "Francio", palabra2: "Fr", descripcion : "---", nivel : 0},
                        {palabra1: "Radio", palabra2: "Ra", descripcion : "---", nivel : 0},
                        {palabra1: "Actinio", palabra2: "Ac", descripcion : "---", nivel : 0},
                        {palabra1: "Torio", palabra2: "Th", descripcion : "---", nivel : 0},
                        {palabra1: "Protactinio", palabra2: "Pa", descripcion : "---", nivel : 0},
                        {palabra1: "Uranio", palabra2: "U", descripcion : "---", nivel : 0},
                        {palabra1: "Neptunio", palabra2: "Np", descripcion : "---", nivel : 0},
                        {palabra1: "Plutonio", palabra2: "Pu", descripcion : "---", nivel : 0},
                        {palabra1: "Americio", palabra2: "Am", descripcion : "---", nivel : 0},
                        {palabra1: "Curio", palabra2: "Cm", descripcion : "---", nivel : 0},
                        {palabra1: "Berkelio", palabra2: "Bk", descripcion : "---", nivel : 0},
                        {palabra1: "Californio", palabra2: "Cf", descripcion : "---", nivel : 0},
                        {palabra1: "Einstenio", palabra2: "Es", descripcion : "---", nivel : 0},
                        {palabra1: "Fermio", palabra2: "Fm", descripcion : "---", nivel : 0},
                        {palabra1: "Mendelevio", palabra2: "Md", descripcion : "---", nivel : 0},
                        {palabra1: "Nobelio", palabra2: "No", descripcion : "---", nivel : 0},
                        {palabra1: "Lawrencio", palabra2: "Lr", descripcion : "---", nivel : 0},
                        {palabra1: "Rutherfordio", palabra2: "Rf", descripcion : "---", nivel : 0},
                        {palabra1: "Dubnio", palabra2: "Db", descripcion : "---", nivel : 0},
                        {palabra1: "Seaborgio", palabra2: "Sg", descripcion : "---", nivel : 0},
                        {palabra1: "Bohrio", palabra2: "Bh", descripcion : "---", nivel : 0},
                        {palabra1: "Hasio", palabra2: "Hs", descripcion : "---", nivel : 0},
                        {palabra1: "Meitnerio", palabra2: "Mt", descripcion : "---", nivel : 0},
                        {palabra1: "Darmstatio", palabra2: "Ds", descripcion : "---", nivel : 0},
                        {palabra1: "Roentgenio", palabra2: "Rg", descripcion : "---", nivel : 0},
                        {palabra1: "Copernicio", palabra2: "Cn", descripcion : "---", nivel : 0},
                        {palabra1: "Nihonio", palabra2: "Nh", descripcion : "---", nivel : 0},
                        {palabra1: "Flerovio", palabra2: "Fl", descripcion : "---", nivel : 0},
                        {palabra1: "Moscovio", palabra2: "Mc", descripcion : "---", nivel : 0},
                        {palabra1: "Livermorio", palabra2: "Lv", descripcion : "---", nivel : 0},
                        {palabra1: "Teneso", palabra2: "Ts", descripcion : "---", nivel : 0},
                        {palabra1: "Oganesón", palabra2: "Og", descripcion : "---", nivel : 0}
    ]
}]
            


// [
//     {ll', palabra2: 'Toro'},
//     {palabra1: 'Cow', palabra2: 'Vaca'},
//     {palabra1: 'Chicken', palabra2: 'Pollo'},
//     {palabra1: 'Hen', palabra2: 'Gallina'},
//     {palabra1: 'Rooster/Cock', palabra2: 'Gallo'},
//     {palabra1: 'Donkey', palabra2: 'Burro'},
//     {palabra1: 'Goat', palabra2: 'Cabra'},
//     {palabra1: 'Horse', palabra2: 'Caballo'},
//     {palabra1: 'Pig', palabra2: 'Cerdo'},
//     {palabra1: 'Rabbit', palabra2: 'Conejo'},
//     {palabra1: 'Sheep', palabra2: 'Oveja'},
//     {palabra1: 'Turkey', palabra2: 'Pavo'},
//     {palabra1: 'Goose', palabra2: 'Ganso'},
//     {palabra1: 'Shrimp', palabra2: 'Camarón'},
//     {palabra1: 'Crab', palabra2: 'Cangrejo'},
//     {palabra1: 'Dolphin', palabra2: 'Delfín'},
//     {palabra1: 'Shark', palabra2: 'Tiburón'},
//     {palabra1: 'Eel', palabra2: 'Anguila'},
//     {palabra1: 'Whale', palabra2: 'Ballena'},
//     {palabra1: 'Killer whale', palabra2: 'Orca'},
//     {palabra1: 'Jellyfish', palabra2: 'Medusa'},
//     {palabra1: 'Lobster', palabra2: 'Langosta'},
//     {palabra1: 'Octopus', palabra2: 'Pulpo'},
//     {palabra1: 'Oyster', palabra2: 'Ostra'},
//     {palabra1: 'Clam', palabra2: 'Almeja'},
//     {palabra1: 'Seal', palabra2: 'Foca'},
//     {palabra1: 'Squid', palabra2: 'Calamar'},
//     {palabra1: 'Cuttlefish', palabra2: 'Sepia'},
//     {palabra1: 'Boar', palabra2: 'Jabalí'},
//     {palabra1: 'Deer', palabra2: 'Ciervo'},
//     {palabra1: 'Mouse', palabra2: 'Ratón'},
//     {palabra1: 'Racoon', palabra2: 'Mapache'},
//     {palabra1: 'Skunk', palabra2: 'Mofeta'},
//     {palabra1: 'Squirrel', palabra2: 'Ardilla'},
//     {palabra1: 'Bat', palabra2: 'Murciélago'},
//     {palabra1: 'Bear', palabra2: 'Oso'},
//     {palabra1: 'Weasel', palabra2: 'Comadreja'},
//     {palabra1: 'Moose', palabra2: 'Alce'},
//     {palabra1: 'Falcon', palabra2: 'Halcón'},
//     {palabra1: 'Eagle', palabra2: 'Águila'},
//     {palabra1: 'Vulture', palabra2: 'Buitre'},
//     {palabra1: 'Hummingbird', palabra2: 'Colibrí'},
//     {palabra1: 'Crow', palabra2: 'Cuervo'},
//     {palabra1: 'Owl', palabra2: 'Búho'},
//     {palabra1: 'Stork', palabra2: 'Cigüeña'},
//     {palabra1: 'Duck', palabra2: 'Pato'},
//     {palabra1: 'Cat', palabra2: 'Gato'},
//     {palabra1: 'Dog', palabra2: 'Perro'},]

